/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Plan } from "./Plan";
import { PlanCountArgs } from "./PlanCountArgs";
import { PlanFindManyArgs } from "./PlanFindManyArgs";
import { PlanFindUniqueArgs } from "./PlanFindUniqueArgs";
import { DeletePlanArgs } from "./DeletePlanArgs";
import { PlanService } from "../plan.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Plan)
export class PlanResolverBase {
  constructor(
    protected readonly service: PlanService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Plan",
    action: "read",
    possession: "any",
  })
  async _plansMeta(
    @graphql.Args() args: PlanCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Plan])
  @nestAccessControl.UseRoles({
    resource: "Plan",
    action: "read",
    possession: "any",
  })
  async plans(@graphql.Args() args: PlanFindManyArgs): Promise<Plan[]> {
    return this.service.plans(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Plan, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Plan",
    action: "read",
    possession: "own",
  })
  async plan(@graphql.Args() args: PlanFindUniqueArgs): Promise<Plan | null> {
    const result = await this.service.plan(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Plan)
  @nestAccessControl.UseRoles({
    resource: "Plan",
    action: "delete",
    possession: "any",
  })
  async deletePlan(@graphql.Args() args: DeletePlanArgs): Promise<Plan | null> {
    try {
      return await this.service.deletePlan(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
